# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directories:
#      - "/mybatis-plus-join-adapter"
      - "/mybatis-plus-join-boot-starter"
      - "/mybatis-plus-join-core"
      - "/mybatis-plus-join-annotation"
      - "/mybatis-plus-join-extension"
      - "/mybatis-plus-join-test"
      - "/plugin/mybatis-plus-join-solon-plugin"
      - "/plugin/mybatis-plus-join-processor"
    schedule:
      interval: "weekly"
