#file: noinspection SpringBootApplicationYaml
spring:
  profiles:
    active: h2
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

mybatis-plus:
  typeEnumsPackage: com.github.yulichang.test
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
    banner: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus-join:
  # 打印 mybatis plus join banner
  banner: true
  sub-table-logic: true
  ms-cache: true
  logic-del-type: where


logging:
  level:
    com.github.yulichang: debug

---
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mpj_test
    username: root
    password: 123456
---
spring:
  profiles: pgsql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mpj_test
    username: postgres
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/pgsql/schema.sql
      data-locations: classpath:db/pgsql/data.sql
---
spring:
  profiles: oracle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/FREE
    username: sys as sysdba
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/oracle/schema.sql
      data-locations: classpath:db/oracle/data.sql